config/routes.rb
JhuproWebsite::Application.routes.draw do
  root to: 'static_pages#home'
  get '/about',   to: 'static_pages#about'
  get '/careers',   to: 'static_pages#career'
  resources :contacts, only: [:new, :create]
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  has_no_table

  column :name, :string
  column :email, :string
  column :subject, :string
  column :message, :string

  attr_accessible :name, :email, :subject, :message

  validates_presence_of :name
  validates_presence_of :email
  validates_presence_of :subject
  validates_presence_of :message
  validates_format_of :email,
                      :with => /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i
  validates_length_of :subject, :maximum => 50
  validates_length_of :message, :maximum => 500

  def update_spreadsheet
    connection = GoogleDrive.login(ENV["EMAIL_USERNAME"], ENV["EMAIL_PASSWORD"])
    ss = connection.spreadsheet_by_title('Website Contact')
    if ss.nil?
      ss = connection.create_spreadsheet('Website Contact')
    end
    ws = ss.worksheets[0]
    last_row = 1 + ws.num_rows
    ws[last_row, 1] = Time.new
    ws[last_row, 2] = self.name
    ws[last_row, 3] = self.email
    ws[last_row, 4] = self.subject
    ws[last_row, 5] = self.message
    ws.save
  end

end

app/models/email_campaign.rb
# == Schema Information
#
# Table name: email_campaigns
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class EmailCampaign < ActiveRecord::Base
  # attr_accessible :title, :body

  def self.add_email_to_website_campaign(email)

    gb = Gibbon::API.new

    result = gb.lists.subscribe({:id => "5fd8f6ff1a", :email => {:email => email}, :double_optin => false})

    rescue Gibbon::MailChimpError => e
    return e

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    if @contact.valid?
      @contact.update_spreadsheet
      UserMailer.contact_email(@contact).deliver
      @message = "Thank you #{@contact.name} for contacting us. We will get back to you shortly."
      respond_to do |format|
        format.html {
          flash[:notice]=@message
          redirect_to root_path
        }
        format.js
      end
    else
      respond_to do |format|
        format.html {render :new}
        format.js
      end
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home

  end

  def about
  end

  def career
  end

  def countdown
    @estimatedTime = "11 April 2014 09:46:35 UTC"
  end

  def emailCampaign
    message = EmailCampaign.add_email_to_website_campaign params[:email]
    render json: message
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "Jhupro"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

  def activeMenu(action, current_link)
    home_menu = "home"
    if action.empty?
      home_menu
    else
      if action==current_link
        'active'
      end
    end
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/contacts/create.js.erb
<% if @message %>
$(".modal-body p").html('<%= escape_javascript @message %>')
<% else %>
$(".modal-body p").html('<%= escape_javascript render('/shared/error_messages', object:@contact) %>')
<% end %>
$('#newsletterModal').modal('show')

app/views/contacts/new.html.erb
<% provide(:title, 'Contact') %>
<header id="page-title" class="nopadding">
    <div id="gmap"><!-- google map --></div>
</header>
<section id="contact" class="container">
    <div class="row">
        <!-- FORM -->
        <div  class="col-md-8">

            <h2>Drop us a line or just say <strong><em>Hello!</em></strong></h2>

            <%=form_for(@contact, html:{class: "white-row", id:"contactForm", novalidate:'novalidate'}, remote:true) do |f|%>
                <%= render 'shared/error_messages', object: f.object %>
                <div class="row">
                    <div class="form-group">
                        <div class="col-md-6">
                            <label>Full Name *</label>
                            <%= f.text_field :name, required:'true', class: 'form-control', id:"name", maxlength:'100', :data=>{:'msg-required'=>"Please enter your name."} %>
                        </div>
                        <div class="col-md-6">
                            <label>E-mail Address *</label>
                            <%= f.email_field :email, required:'true', class: 'form-control', id:"email", maxlength:'100', :data=>{:'msg-required'=>"Please enter your email address.", :'msg-email'=>'Please enter a valid email address.'} %>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group">
                        <div class="col-md-12">
                            <label>Subject *</label>
                            <%= f.text_field :subject, required:'true', class: 'form-control', id:"subject", maxlength:'100', :data=>{:'msg-required'=>"Please enter the subject."} %>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group">
                        <div class="col-md-12">
                            <label>Message *</label>
                            <%= f.text_area :message, required:'true', class: 'form-control', id:"message",rows:'10', maxlength:'5000', :data=>{:'msg-required'=>"Please enter your message."} %>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <%= f.submit 'Send Message', class:'btn btn-primary btn-lg', data:{disable_with: 'Loading...'} %>
                    </div>
                </div>
            <%end%>
        </div>
        <!-- /FORM -->


        <!-- INFO -->
        <div class="col-md-4">

            <h2>Visit Us</h2>
            <p>
                We are located in one of the cleanest city of Nepal. Feel free to visit us whenever you are free.
            </p>
            <div class="divider half-margins"><!-- divider -->
                <i class="fa fa-star"></i>
            </div>
            <p>
                <span class="block"><strong><i class="fa fa-map-marker"></i> Address:</strong> Parijat Marg, Hetauda, Makawanpur, Nepal</span>
                <span class="block"><strong><i class="fa fa-phone"></i> Phone:</strong>977-9806855468</span>
                <span class="block"><strong><i class="fa fa-envelope"></i> Email:</strong><%=link_to "info@jhupro.com", "mailto:info@jhupro.com"%></span>
            </p>
            <div class="divider half-margins"><!-- divider -->
                <i class="fa fa-star"></i>
            </div>
            <h4 class="font300">Business Hours</h4>
            <p>
                <span class="block"><strong>Sunday - Friday:</strong> 10am to 5pm</span>
                <span class="block"><strong>Saturday:</strong> Closed</span>
            </p>
        </div>
        <!-- /INFO -->
    </div>
</section>

<!-- /WRAPPER -->


<div class="modal fade contactModal" id="newsletterModal" tabindex="-1" role="dialog" aria-labelledby="myNewsletterLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">

            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title" id="myNewsletterLabel"><i class="fa fa-envelope-o"></i> <span class="font600">Contact</span></h4>
            </div>

            <div class="modal-body">

                <p>
                    Thank you for contacting us!
                </p>

            </div>

            <div class="modal-footer">
                <button class="btn btn-default btn-sm fullwidth" data-dismiss="modal">OK, CLOSE</button>
            </div>

        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div>

app/views/layouts/_footer.html.erb
<!-- FOOTER -->
<footer>
    <!-- copyright , scrollTo Top -->
    <div class="footer-bar">
        <div class="container">
            <span class="copyright">Copyright &copy; Jhupro Services Pvt Ltd. All Rights Reserved.</span>
            <a class="toTop" href="#topNav">BACK TO TOP <i class="fa fa-arrow-circle-up"></i></a>
        </div>
    </div>
    <!-- copyright , scrollTo Top -->
    <!-- footer content -->
    <div class="footer-content">
        <div class="container">
            <div class="row">
                <!-- FOOTER CONTACT INFO -->
                <div class="column col-md-4">
                    <h3>CONTACT</h3>

                    <p class="contact-desc">
                        Nepal Office
                    </p>
                    <address class="font-opensans">
                        <ul>
                            <li class="footer-sprite address">
                                Parijat Marg<br />
                                Hetauda, Makawanpur<br />
                                Nepal<br />
                            </li>
                            <li class="footer-sprite phone">
                                Phone: 977-9806855468
                            </li>
                            <li class="footer-sprite email">
                                <%=link_to "info@jhupro.com", "mailto:info@jhupro.com"%>
                            </li>
                        </ul>
                    </address>
                </div>
                <!-- FOOTER LOGO -->
                <div class="column logo col-md-4 text-center">
                    <div class="logo-content">
                        <%= image_tag("logo-text-bottom.png",
                                      {class: "animate_fade_in", alt: "Jhupro", width: "300"}) %>
                        <h4>Professional | Friendly | Suitable</h4>
                    </div>
                </div>
                <!-- /FOOTER LOGO -->

                <!-- FOOTER LATEST POSTS -->
                <div class="column col-md-4 text-right">
                    <h3>CONTACT</h3>
                    <p class="contact-desc">
                        US Office
                    </p>
                    <address class="font-opensans pull-right">
                        <ul>
                            <li class="footer-sprite address">
                                2400 South Avenue A<br />
                                Yuma, AZ 85364<br />
                                United States<br />
                            </li>
                            <li class="footer-sprite phone">
                                Phone: (928) 336-2000
                            </li>
                            <li class="footer-sprite email">
                                <%=link_to "bibek.jhupro@gmail.com", "mailto:bibek.jhupro@gmail.com"%>
                            </li>
                        </ul>
                    </address>
                </div>
                <!-- /FOOTER LATEST POSTS -->
            </div>
        </div>
    </div>
    <!-- footer content -->
</footer>
<!-- /FOOTER -->

app/views/layouts/_googleAnalytics.html.erb
<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-48812438-1', 'jhupro.com');
    ga('require', 'linkid', 'linkid.js');
    ga('send', 'pageview');

</script>

app/views/layouts/_header.html.erb
<!-- TOP NAV -->
<header id="topNav">
    <div class="container">
        <!-- Mobile Menu Button -->
        <button class="btn" data-toggle="collapse" data-target=".nav-main-collapse">
            <i class="fa fa-bars"></i>
        </button>
        <!-- Logo text or image -->
       <%= link_to image_tag('jhupro.png', {alt:'Jhupro', style:'height:50px;'}), root_path, class:'logo'%>
        <!-- Top Nav -->

        <div class="navbar-collapse nav-main-collapse collapse pull-right">
            <nav class="nav-main mega-menu">
                <ul class="nav nav-pills nav-main scroll-menu" id="topMain">
                    <li class="<%=activeMenu(params[:action],'home')%>"><%= link_to 'Home', root_path %></li>
                    <li class="<%=activeMenu(params[:action],'about')%>"><%= link_to 'About Us', about_path%></li>
                    <li class="<%=activeMenu(params[:action],'new')%>"><%= link_to 'Contact', new_contact_path%></li>
                    <li class="<%=activeMenu(params[:action],'career')%>"><%= link_to 'Careers', careers_path%></li>
                </ul>
            </nav>
        </div>
        <!-- /Top Nav -->
    </div>
</header>
<span id="header_shadow"></span>
<!-- /TOP NAV -->

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name == :notice ? "success" : "warning" %>" role="alert">
            <%= content_tag :div, msg %>
        </div>
    <% end %>
<% end %>

app/views/layouts/_shim.html.erb
<!--[if IE 8]>			<html class="ie ie8"> <![endif]-->
<!--[if IE 9]>			<html class="ie ie9"> <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<%= render 'layouts/shim' %>
<!--[if gt IE 9]><!--><html><!--<![endif]-->
<head >

    <meta charset="utf-8" />
    <title><%= full_title(yield (:title)) %></title>
    <meta name="keywords" content="jhupro, jhupro services, web, web app, website, website development, web development services, web application development, mobile application development, software services, it services, outsourcing nepal" />
    <meta name="description" content="Jhupro is a web application development company focused on delivering professional, friendly and suitable applications." />
    <meta name="author" content="jhupro" />
    <!-- Open Graph -->
    <meta property="og:description" content="Jhupro is a web application development company focused on delivering professional, friendly and suitable applications." />
    <meta property='og:locale' content='en_US'/>
    <meta property='og:url' content='http://www.jhupro.com'/>
    <meta property='og:site_name' content='jhupro'/>
    <meta property='og:type' content='website'/>
    <link href="https://plus.google.com/110086904451751216460" rel="publisher" />
    <%=favicon_link_tag 'favicon.ico'%>
    <!-- mobile settings -->
    <meta name="viewport" content="width=device-width, maximum-scale=1, initial-scale=1, user-scalable=0" />
    <!-- WEB FONTS -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700,800" rel="stylesheet" type="text/css" />
    <!--/web fonts-->
    <!-- style sheets-->
    <%= stylesheet_link_tag "application", :media => "all" %>
    <!--/style sheets-->
    <!--javascripts-->
    <%= javascript_include_tag "plugins/modernizr.min.js" %>
    <script type="text/javascript">
       (function() {
           var po = document.createElement("script"); po.type = "text/javascript"; po.async = true;
            po.src = "https://apis.google.com/js/plusone.js?publisherid=110086904451751216460";
            var s = document.getElementsByTagName("script")[0]; s.parentNode.insertBefore(po, s);
                 })();
    </script>
    <!--/javascripts-->
    <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<!-- WRAPPER -->
<div id="wrapper" >
    <%= render 'layouts/messages'%>
    <%= yield %>
</div>
<!-- /WRAPPER -->
<%= render 'layouts/footer' %>

<!-- javascripts -->
<%= javascript_include_tag "application" %>
<!-- /javascripts -->
<%= render 'layouts/googleAnalytics' %>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-error">
            The form contains <%= pluralize(object.errors.count, "error") %>.
        </div>
        <ul>
            <% object.errors.full_messages.each do |msg| %>
                <li>* <%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/static_pages/career.erb
<% provide(:title, 'Careers') %>
<!-- PAGE TITLE -->
<header id="page-title">

    <div class="container">
        <h1>Careers</h1>

        <ul class="breadcrumb">
            <li><%=link_to "Home", root_path%></li>
            <li class="active">Careers</li>
        </ul>
    </div>
</header>

<section class="container">

    <h2><strong>C</strong>areers <strong>A</strong>t <strong>J</strong>hupro</h2>

    <p class="lead">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur pellentesque neque eget diam
        posuere porta. Quisque ut nulla at nunc vehicula lacinia. Proin adipiscing porta tellus, ut feugiat nibh
        adipiscing sit amet.</p>

    <div class="divider"><!-- divider -->
        <i class="fa fa-star"></i>
    </div>

    <div class="toogle">

        <div class="toggle active">
            <label>Why Jhupro is the best choice for you?</label>
            <div class="toggle-content">
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur pellentesque neque eget diam
                    posuere porta. Quisque ut nulla at nunc vehicula lacinia. Proin adipiscing porta tellus, ut feugiat
                    nibh adipiscing sit amet.</p>
                <%= link_to image_tag('career/jhupro_dark_small.png', {alt:'Jhupro', style:'height:110px;'}),
                            image_path('home/jhupro_dark.png'), class:'img-thumbnail lightbox pull-left inner',
                            data:{:'plugin-options'=>'{"type"":"image"}'}%>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur pellentesque neque eget diam posuere
                    porta. Quisque ut nulla at nunc vehicula lacinia. Proin adipiscing porta tellus, ut feugiat nibh
                    adipiscing sit amet.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur
                    <%=link_to "pellentesque neque eget", "javascript:void(0);", data:{toggle:"tooltip",
                                                                                       :'original-title'=>'Default tooltip'} %>
                    diam posuere porta. Quisque ut nulla at nunc vehicula lacinia. Proin adipiscing porta tellus, ut feugiat
                    nibh adipiscing sit amet.
                    <%=link_to "Popover on top", "javascript:void(0);", title:'A Title',
                               data:{toggle:"popover", :'original-title'=>'A Title',
                                     content:"And here's some amazing content. It's very engaging. right?",
                                     placement:"top", container:"body"} %>
                </p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur pellentesque neque eget
                    diam posuere porta. Quisque ut nulla at nunc vehicula lacinia. Proin adipiscing porta tellus, ut
                    feugiat nibh adipiscing sit amet.</p>

                <div class="divider styleColor white"><!-- divider -->
                    <i class="fa fa-leaf"></i>
                </div>

                <!-- columns -->
                <div class="row">
                    <div class="col-md-4"><!-- left -->
                        <h3>Alien Features</h3>
                        <p class="justify">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur
                            pellentesque neque eget diam posuere porta. Quisque ut nulla at nunc vehicula lacinia. Proin
                            adipiscing porta tellus, ut feugiat nibh adipiscing sit amet.</p>
                    </div>
                    <div class="col-md-4"><!-- center - logo -->
                        <%= image_tag("logo-text-bottom.png",
                                      {class: "animate_fade_in", alt: "Jhupro", width: "300"}) %>
                    </div>
                    <div class="col-md-4"><!-- right -->
                        <h3>Human Features</h3>
                        <p class="justify">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur
                            pellentesque neque eget diam posuere porta. Quisque ut nulla at nunc vehicula lacinia. Proin
                            adipiscing porta tellus, ut feugiat nibh adipiscing sit amet.</p>
                    </div>
                </div>

                <p class="lead padding30 text-center">Yes, Jhupro can be customized very easy in many ways.</p>
            </div>
        </div>

        <div class="toggle">
            <label>Lorem ipsum dolor sit amet, consectetur adipiscing elit?</label>
            <div class="toggle-content">
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur
                    <%=link_to "pellentesque neque eget", "javascript:void(0);", data:{toggle:"tooltip",
                                                                                       :'original-title'=>'Default tooltip'} %>
                    diam posuere porta. Quisque ut nulla at nunc vehicula lacinia. Proin adipiscing porta tellus, ut feugiat
                    nibh adipiscing sit amet.
                    <%=link_to "Popover on top", "javascript:void(0);", title:'A Title',
                               data:{toggle:"popover", :'original-title'=>'A Title',
                                     content:"And here's some amazing content. It's very engaging. right?",
                                     placement:"top", container:"body"} %>
                </p>
                <ul class="list-icon check StyleSecondColor">
                    <li>Nullam id dolor id</li>
                    <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit</li>
                    <li>Maecenas sed diam eget</li>
                    <li>Curabitur pellentesque neque eget diam posuere porta.</li>
                </ul>
            </div>
        </div>

        <div class="toggle">
            <label>Curabitur pellentesque neque eget diam?</label>
            <div class="toggle-content">
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur
                    <%=link_to "pellentesque neque eget", "javascript:void(0);", data:{toggle:"tooltip",
                                                                                       :'original-title'=>'Default tooltip'} %>
                    diam posuere porta. Quisque ut nulla at nunc vehicula lacinia. Proin adipiscing porta tellus, ut feugiat
                    nibh adipiscing sit amet.
                    <%=link_to "Popover on top", "javascript:void(0);", title:'A Title',
                               data:{toggle:"popover", :'original-title'=>'A Title',
                                     content:"And here's some amazing content. It's very engaging. right?",
                                     placement:"top", container:"body"} %>
                </p>
                <ul class="list-icon check StyleSecondColor">
                    <li>Nullam id dolor id</li>
                    <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit</li>
                    <li>Maecenas sed diam eget</li>
                    <li>Curabitur pellentesque neque eget diam posuere porta.</li>
                </ul>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur
                    <%=link_to "pellentesque neque eget", "javascript:void(0);", data:{toggle:"tooltip",
                                                                                       :'original-title'=>'Default tooltip'} %>
                    diam posuere porta. Quisque ut nulla at nunc vehicula lacinia. Proin adipiscing porta tellus, ut feugiat
                    nibh adipiscing sit amet.
                    <%=link_to "Popover on top", "javascript:void(0);", title:'A Title',
                               data:{toggle:"popover", :'original-title'=>'A Title',
                                     content:"And here's some amazing content. It's very engaging. right?",
                                     placement:"top", container:"body"} %>
                </p>
            </div>
        </div>
    </div>
    <!-- CALLOUT -->
    <div class="bs-callout text-center nomargin-bottom">
        <h3>
            <strong>Apply</strong> with your resume today! <strong>977-9806855468</strong>
        </h3>

        <div class="divider"><!-- divider -->
            <i class="fa fa-chevron-down"></i>
        </div>

        <h3>
            <%=link_to "Apply", "mailto:info@jhupro.com", class:"btn btn-primary btn-lg", target:"_blank"%>
        </h3>
    </div>
    <!-- /CALLOUT -->

</section>

app/views/static_pages/countdown.html.erb
<div class="special-page container">

    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="center-box">
                <h1>COMING SOON</h1>

                <!-- Countdown -->
                <div id="countdown">
                    <div class="countdown-widget" id="countdown-widget" data-time="<%=@estimatedTime%>"></div>
                </div>
                <!-- /Countdown -->

                <hr />

                <div class="row">
                    <div class="col-md-6 text-left">
                        <h2>Let me know <strong>when</strong> the site is done</h2>

                        <%=form_tag({controller: "static_pages", action: "emailCampaign"}, method: "posts", class: "input-group", id:"countdownForm") do %>
                            <%= text_field_tag 'email', nil, placeholder: 'E-mail Address', type:'email', required:'true', class: 'form-control' %>
                            <span class="input-group-btn">
                                <%= button_tag(type: "submit", class: "btn btn-primary") do %>
                                       <i class="fa fa-search"></i>
                                <% end %>
							</span>
                        <% end %>
                        <p class="font300">Type your best E-mail Address</p>

                    </div>
                    <div class="col-md-6 text-left">
                        <h2>Some additional <strong>Info</strong></h2>

                        <p>We're not <strong>quite</strong> there yet - <strong>but we're getting there!</strong> - and we <strong>really</strong> want you to know when we’re ready.</p>
                    </div>
                </div>

                <hr />

                <div class="row text-left">
                    <div class="col-md-12">

                        <div class="progress-bars">
                            <div class="progress-label">
                                <span>Conception</span>
                            </div>
                            <div class="progress">
                                <div class="progress-bar progress-bar-primary" data-appear-progress-animation="70%">
                                    <span class="progress-bar-tooltip">70%</span>
                                </div>
                            </div>
                            <div class="progress-label">
                                <span>Design</span>
                            </div>
                            <div class="progress">
                                <div class="progress-bar progress-bar-primary" data-appear-progress-animation="60%" data-appear-animation-delay="100">
                                    <span class="progress-bar-tooltip">60%</span>
                                </div>
                            </div>
                            <div class="progress-label">
                                <span>Coding</span>
                            </div>
                            <div class="progress">
                                <div class="progress-bar progress-bar-primary" data-appear-progress-animation="62%" data-appear-animation-delay="200">
                                    <span class="progress-bar-tooltip">62%</span>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>

            </div>
        </div>
    </div>

</div>


<section id="slider" class="nomargin-top fixed full-screen" data-autoplay="9000"><!-- data-autoplay = 'false' or miliseconds. Eg.: 5s = '5000' -->
    <ul class="slides-container">
        <li>
            <span class="overlay"></span>
            <div style="background-image: url(<%= asset_path 'covers/cover_1.jpg' %>)" class="fullscreen-img"></div>
        </li>
        <li>
            <span class="overlay"></span>
            <div style="background-image: url(<%= asset_path 'covers/cover_2.jpg' %>);" class="fullscreen-img"></div>
        </li>
        <li>
            <span class="overlay"></span>
            <div style="background-image: url(<%= asset_path 'covers/cover_3.jpg' %>);" class="fullscreen-img"></div>
        </li>
        <li>
            <span class="overlay"></span>
            <div style="background-image: url(<%= asset_path 'covers/cover_4.jpg' %>);" class="fullscreen-img"></div>
        </li>
    </ul>
</section>

<!-- NEWSLETTER MODAL -->
<div class="modal fade contactModal" id="newsletterModal" tabindex="-1" role="dialog" aria-labelledby="myNewsletterLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">

            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title" id="myNewsletterLabel"><i class="fa fa-envelope-o"></i> <span class="font600">Subscribed</span></h4>
            </div>

            <div class="modal-body">

                <p>
                    Thank you for your subscription!
                </p>

            </div>

            <div class="modal-footer">
                <button class="btn btn-default btn-sm fullwidth" data-dismiss="modal">OK, CLOSE</button>
            </div>

        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div>
<!-- /NEWSLETTER MODAL -->